## LATIHAN

## 1.Perkalian Matrix

In [5]:
import numpy as np
A = np.array([15, 7, 5])

B = np.array([19, 42, 95])

# Mengalikan matriks A dan B

kali = A * B
print(kali)


[285 294 475]


## 2.Pengurangan Matrix

In [3]:
import numpy as np

A = np.array([[15, 7, 5]])
B = np.array([[19, 42, 95]])

kurang = A - B
print(kurang)

[[ -4 -35 -90]]


## 3.Transpose Matrix

In [7]:
import numpy as np

A = np.array([15, 7, 5])
B = np.array([19,42, 5])

transpose_A = np.transpose(A)
print(transpose_A)

[15  7  5]


## 4.Nilai Invers

In [8]:
A = np.array([[15,75], [42,95]])

inverse_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print(inverse_A)


invers matriks A:
[[-0.05507246  0.04347826]
 [ 0.02434783 -0.00869565]]


## 5.Nilai Determinan

In [9]:
import numpy as np

A = np.array([[15,75], [42,95]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: -1724.9999999999993
